version: '3.3'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_PASSWORD=Admin123
      - POSTGRES_USER=Admin
      - POSTGRES_DB=odoo_db
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  odoo:
    image: elestio/odoo:latest
    restart: always
    depends_on:
      - db
    ports:
      - "8069:8069"
    tty: true
    command: -- --dev=reload
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=Admin123
    networks:
      - default
