#-----------------------------------------------------------------------------------
# On donne le nom "wordpress" à ce container,
# à partir de l'image "wordpress",
# on le lie à notre bdd nommée "db",
# sur le port 8081 de notre machine, qui pointe sur le port 80 de notre "container",
# puis pour finir on copie le "volume".
#-----------------------------------------------------------------------------------
# On donne le nom "wpmariadb" à ce container,
# à partir de la dernière image "mariadb",
# on init une variable "MYSQL_ROOT_PASSWORD = root",
# sur le port 3306 de notre machine, qui pointe sur le port 3306 de notre "container".
#-----------------------------------------------------------------------------------
# On donne le nom "wpphpmyadmin" à ce "container",
# à partir de l'image "phpmyadmin/phpmyadmin",
# on le lie à notre bdd nommée "db",
# on init 2 variables "MYSQL_USERNAME= root" et "MYSQL_ROOT_PASSWORD=root",
# sur le port 8080 de notre machine, qui pointe sur le port 80 de notre "container",
# on crée un volume "/sessions".
#-----------------------------------------------------------------------------------

#wordpress:
#    image: wordpress
#    links:
#        - "db:mysql"
#    ports:
#        - "4040:80"
#    volumes:
        # copy in path windows
#        - ~/Documents/docker/wordpress/:/var/www/html/

db:
    image: mariadb:latest
    container_name: mariadb
    environment:
        MYSQL_ROOT_PASSWORD: root
    ports:
        - "4040:3306"

phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    links:
        - "db:db"
    environment:
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: root
    restart: always
    ports:
        - "2020:80"
    volumes:
        - "/sessions"