apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-memcached
  name: my-memcached
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-memcached
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-memcached
    spec:
      containers:
      - image: memcached:latest
        name: memcached
        resources: {}
status: {}
