apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-08-27T20:50:32Z"
  labels:
    app: my-nginx
  name: svc-my-nginx
  namespace: default
  resourceVersion: "12105"
  selfLink: /api/v1/namespaces/default/services/svc-my-nginx
  uid: 6af22bc6-77b1-4e5c-96eb-6fec651dbf72
spec:
  clusterIP: 10.109.176.129
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: my-nginx
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
