services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=dolibarr
      - MYSQL_USER=dolibarr
      - MYSQL_PASSWORD=4caracteresetcestbon
      #- MYSQL_ROOT_PASSWORD=5caracteresetcestbon
    volumes:
      - ./dolibarr_db:/var/lib/mysql:rw
    networks:
      - dolibarr-network
    ports:
      - "3306:3306"

  dolibarr:
    image: tuxgasy/dolibarr:19.0.2
    container_name: dolibarr
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8200:80"
    environment:
      - DOLI_INSTALL_AUTO=1
      - DOLI_DB_TYPE=mysqli
    #  - DOLI_DB_PREFIX='table'
    #  - DOLI_DB_CHARACTER_SET=utf8
    #  - DOLI_DB_COLLATION=utf8_unicode_ci
      #- DOLI_DB_ROOT_LOGIN=root
      #- DOLI_DB_ROOT_PASSWORD=5caracteresetcestbon
      - DOLI_PROD=1
      #- DOLI_ADMIN_LOGIN=admin
      #- DOLI_ADMIN_PASSWORD=admin
      - DOLI_DB_HOST=mariadb
      - DOLI_DB_NAME=dolibarr
      - DOLI_DB_USER=dolibarr
      - DOLI_DB_PASSWORD=4caracteresetcestbon
      - PHP_INI_DATE_TIMEZONE=Europe/Brussels
      #- DOLI_HTTPS=0
      - DOLI_HTTPS=1
      #- DOLI_HTTPS=2
      - DOLI_HTTPS=https://doyouwannaplaywith.me
    volumes:
      - ./dolibarr_home:/home:rw
      - dolibarr_html:/var/www/html:rw
      - dolibarr_docs:/var/www/documents:rw
      - dolibarr_website:/var/www/html/website:rw
    networks:
      - dolibarr-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    networks:
      - dolibarr-network
    ports:
      - "8211:80"
    environment:
      - PMA_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=5caracteresetcestbon

volumes:
  dolibarr_home:
  dolibarr_db:
  dolibarr_docs:
  dolibarr_website:
  dolibarr_html:

networks:
  dolibarr-network:
    driver: bridge
