version: '3'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=dolibarr
      - MYSQL_USER=dolibarr
      - MYSQL_PASSWORD=4caracteresetcestbon
      - MYSQL_ROOT_PASSWORD=5caracteresetcestbon
    volumes:
      - ./dolibarr_db:/var/lib/mysql
    networks:
      - dolibarr-network

  dolibarr:
    image: tuxgasy/dolibarr:latest
    container_name: dolibarr
    restart: always
    links:
      - mariadb
    ports:
      - "8200:80"
    environment:
      - DOLI_INSTALL_AUTO=1
      - DOLI_ADMIN_LOGIN=admin
      - DOLI_ADMIN_PASSWORD=admin
      - DOLI_DB_HOST=mariadb
      - DOLI_DB_NAME=dolibarr
      - DOLI_DB_USER=dolibarr
      - DOLI_DB_PASSWORD=4caracteresetcestbon
      - PHP_INI_DATE_TIMEZONE=Europe/Brussels
      - DOLI_HTTPS=https://doyouwannaplaywith.me
    volumes:
      - dolibarr_html:/var/www/html
      - dolibarr_docs:/var/www/documents
    networks:
      - dolibarr-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8211:80"
    environment:
      - PMA_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=5caracteresetcestbon
    networks:
      - dolibarr-network
    depends_on:
      - mariadb

volumes:
  dolibarr_html:
  dolibarr_docs:

networks:
  dolibarr-network:
    driver: bridge
